
 (customize-set-variable 'ag-arguments (quote ("--line-number" "--smart-case" "--column" "--nogroup")))
 (customize-set-variable 'ag-highlight-search t)
 (customize-set-variable 'ag-ignore-list (quote ("build/*" "*.ipynb" "core.*" "core")))
 (customize-set-variable 'ag-project-root-function (quote project-root-helper))
 (customize-set-variable 'ag-reuse-buffers t)
 (customize-set-variable 'blink-cursor-mode nil)
 (customize-set-variable 'c-syntactic-indentation t)
 (customize-set-variable 'c-tab-always-indent t)
 (customize-set-variable 'company-auto-complete (quote (quote company-explicit-action-p)))
 (customize-set-variable 'compilation-always-kill t)
 (customize-set-variable 'compilation-auto-jump-to-first-error nil)
 (customize-set-variable 'compilation-environment nil)
 (customize-set-variable 'compilation-scroll-output (quote first-error))
 (customize-set-variable 'compilation-search-path (quote (nil "/usr/bin/" "/opt/local/bin/")))
 (customize-set-variable 'compilation-skip-threshold 2)
 (customize-set-variable 'current-language-environment "UTF-8")
 (customize-set-variable 'custom-enabled-themes (quote (wombat)))
 (customize-set-variable 'custom-safe-themes t)
 (customize-set-variable 'delete-selection-mode nil)
 (customize-set-variable 'doc-view-continuous t)
 (customize-set-variable 'doxymacs-command-character "\\")
 (customize-set-variable 'ediff-custom-diff-options "-c  -w")
 (customize-set-variable 'ediff-diff-options "-w")
 (customize-set-variable 'ediff-split-window-function (quote split-window-horizontally))
 (customize-set-variable 'explicit-bash-args (quote ("--noediting" "-i")))
 (customize-set-variable 'explicit-shell-file-name nil)
 (customize-set-variable 'fill-column 79)
 (customize-set-variable 'flymake-gui-warnings-enabled nil)
 (customize-set-variable 'global-highlight-changes-mode t)
 (customize-set-variable 'highlight-changes-visibility-initial-state nil)
 (customize-set-variable 'ido-auto-merge-delay-time 10)
 (customize-set-variable 'ido-enter-matching-directory (quote only))
 (customize-set-variable 'ido-everywhere t)
 (customize-set-variable 'ido-use-filename-at-point (quote guess))
 (customize-set-variable 'ido-use-url-at-point t)
 (customize-set-variable 'indent-tabs-mode nil)
 (customize-set-variable 'ispell-dictionary "deutsch")
 (customize-set-variable 'ispell-extra-args nil)
 (customize-set-variable 'ispell-program-name "/usr/bin/aspell")
 (customize-set-variable 'load-home-init-file t t)
 (customize-set-variable 'mark-even-if-inactive t)
 (customize-set-variable 'preview-gs-command "/opt/local/bin/gs")
 (customize-set-variable 'projectile-bzr-command "true")
 (customize-set-variable 'projectile-darcs-command "true")
 (customize-set-variable 'projectile-enable-caching t)
 (customize-set-variable 'projectile-git-command "true")
 (customize-set-variable 'projectile-hg-command "true")
 (customize-set-variable 'projectile-indexing-method (quote native))
 (customize-set-variable 'projectile-project-root-files (quote ("rebar.config" "project.clj" "pom.xml" "build.sbt" "build.gradle" "Gemfile" "requirements.txt" "package.json" "gulpfile.js" "Gruntfile.js" "bower.json" "composer.json" "SConstruct" "lastPerformance.pdf" "run.log")))
 (customize-set-variable 'projectile-project-root-files-bottom-up (quote (".projectile" ".git" ".hg" ".fslckout" ".bzr" "_darcs" "SConstruct" "setup.py")))
 (customize-set-variable 'projectile-project-root-files-top-down-recurring (quote ("CVS" "SConscript")))
 (customize-set-variable 'ps-paper-type (quote a4))
 (customize-set-variable 'ps-print-color-p nil)
 (customize-set-variable 'recentf-initialize-file-name-history t)
 (customize-set-variable 'recentf-max-saved-items 8)
 (customize-set-variable 'recentf-mode t)
 (customize-set-variable 'reftex-plug-into-AUCTeX t)
 (customize-set-variable 'safe-local-variable-values (quote ((emacs-lisp-docstring-fill-column . 75))))
 (customize-set-variable 'scroll-bar-mode (quote right))
 (customize-set-variable 'semantic-c-dependency-system-include-path (quote ("/usr/include")))
 (customize-set-variable 'semantic-decoration-styles (quote (("semantic-decoration-on-includes" . t) ("semantic-decoration-on-protected-members" . t) ("semantic-decoration-on-private-members" . t) ("semantic-tag-boundary" . t))))
 (customize-set-variable 'semantic-idle-scheduler-idle-time 1)
 (customize-set-variable 'semantic-idle-scheduler-work-idle-time 60)
; (customize-set-variable 'show-paren-mode t nil (paren))
 (customize-set-variable 'transient-mark-mode 1)
 (customize-set-variable 'user-full-name "Lukas Schuller")
 (customize-set-variable 'visible-cursor nil)
 (customize-set-variable 'void-text-area-pointer (quote arrow))



;; (custom-set-faces
;;  ;; custom-set-faces was added by Custom.
;;  ;; If you edit it by hand, you could mess it up, so be careful.
;;  ;; Your init file should contain only one such instance.
;;  ;; If there is more than one, they won't work right.
;;  '(compilation-info ((t (:foreground "#cae682"))))
;;  '(cursor ((t (:background "gray40"))))
;;  '(error ((t (:foreground "firebrick2" :weight bold))))
;;  '(ido-first-match ((t (:weight extra-bold))))
;;  '(ido-only-match ((t (:foreground "ForestGreen" :weight bold))))
;;  '(ido-subdir ((t (:inherit font-lock-warning-face)))))
